# Generated by Django 3.1.5 on 2021-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
